import {
  Activity,
  AppWindow,
  Archive,
  Bell,
  Box,
  Boxes,
  Braces,
  Brain,
  Bug,
  Calendar,
  Clock,
  Cloud,
  Code,
  Cog,
  Container,
  Cpu,
  CreditCard,
  Database,
  FileText,
  Folder,
  Gauge,
  GitBranch,
  Globe,
  HardDrive,
  Inbox,
  Key,
  Layers,
  Link,
  List,
  Lock,
  Map as MapIcon,
  Mail,
  MessageSquare,
  Monitor,
  Network,
  Package,
  Search,
  Send,
  Server,
  Settings,
  Shield,
  Smartphone,
  Star,
  Table,
  Terminal,
  Timer,
  Truck,
  User,
  Users,
  Webhook,
  Wifi,
  Workflow,
  Wrench,
  Zap,
  type LucideIcon,
} from 'lucide-react';

const ICONS: Record<string, LucideIcon> = {
  activity: Activity,
  monitoring: Activity,
  metrics: Activity,
  observability: Activity,
  chart: Activity,
  analytics: Gauge,
  gauge: Gauge,
  api: Braces,
  function: Braces,
  lambda: Braces,
  braces: Braces,
  app: AppWindow,
  browser: AppWindow,
  frontend: AppWindow,
  web: AppWindow,
  ui: AppWindow,
  archive: Archive,
  backup: Archive,
  bell: Bell,
  notification: Bell,
  alert: Bell,
  box: Box,
  boxes: Boxes,
  cluster: Boxes,
  kubernetes: Boxes,
  k8s: Boxes,
  brain: Brain,
  ai: Brain,
  ml: Brain,
  model: Brain,
  llm: Brain,
  bug: Bug,
  calendar: Calendar,
  clock: Clock,
  cron: Timer,
  timer: Timer,
  scheduler: Timer,
  cloud: Cloud,
  aws: Cloud,
  gcp: Cloud,
  azure: Cloud,
  code: Code,
  container: Container,
  docker: Container,
  cpu: Cpu,
  compute: Cpu,
  payment: CreditCard,
  billing: CreditCard,
  card: CreditCard,
  database: Database,
  db: Database,
  postgres: Database,
  mysql: Database,
  sql: Database,
  mongo: Database,
  mongodb: Database,
  file: FileText,
  document: FileText,
  docs: FileText,
  folder: Folder,
  git: GitBranch,
  repo: GitBranch,
  globe: Globe,
  internet: Globe,
  dns: Globe,
  cdn: Globe,
  edge: Globe,
  storage: HardDrive,
  disk: HardDrive,
  s3: HardDrive,
  bucket: HardDrive,
  blob: HardDrive,
  inbox: Inbox,
  key: Key,
  secret: Key,
  secrets: Key,
  token: Key,
  layers: Layers,
  stack: Layers,
  link: Link,
  queue: List,
  kafka: List,
  sqs: List,
  rabbitmq: List,
  list: List,
  lock: Lock,
  auth: Lock,
  security: Lock,
  iam: Lock,
  mail: Mail,
  email: Mail,
  smtp: Mail,
  map: MapIcon,
  geo: MapIcon,
  message: MessageSquare,
  chat: MessageSquare,
  sms: MessageSquare,
  monitor: Monitor,
  desktop: Monitor,
  dashboard: Monitor,
  network: Network,
  vpc: Network,
  subnet: Network,
  lb: Network,
  'load-balancer': Network,
  loadbalancer: Network,
  gateway: Network,
  proxy: Network,
  package: Package,
  artifact: Package,
  registry: Package,
  search: Search,
  elasticsearch: Search,
  elastic: Search,
  send: Send,
  publish: Send,
  server: Server,
  vm: Server,
  host: Server,
  backend: Server,
  service: Server,
  settings: Settings,
  config: Settings,
  gear: Cog,
  cog: Cog,
  worker: Cog,
  shield: Shield,
  firewall: Shield,
  waf: Shield,
  mobile: Smartphone,
  phone: Smartphone,
  ios: Smartphone,
  android: Smartphone,
  star: Star,
  table: Table,
  terminal: Terminal,
  cli: Terminal,
  shell: Terminal,
  truck: Truck,
  delivery: Truck,
  user: User,
  customer: User,
  client: User,
  users: Users,
  customers: Users,
  clients: Users,
  team: Users,
  webhook: Webhook,
  wifi: Wifi,
  iot: Wifi,
  workflow: Workflow,
  pipeline: Workflow,
  etl: Workflow,
  wrench: Wrench,
  tools: Wrench,
  zap: Zap,
  cache: Zap,
  redis: Zap,
};

// Fallbacks so provider-prefixed names (aws-rds, azure-sql-database, ...) land on a sensible glyph.
const PATTERNS: Array<[RegExp, LucideIcon]> = [
  [/dynamo|rds|aurora|cosmos|spanner|bigtable|postgre|maria|database|sql|firestore/, Database],
  [/s3\b|simple-storage|glacier|storage|blob|bucket|filestore/, HardDrive],
  [/lambda|function|faas/, Braces],
  [/ec2|compute|instance|fargate|app-service|\bvm\b/, Server],
  [/sqs|sns|queue|pub-?sub|kinesis|event|kafka|rabbit/, List],
  [/cloudfront|cdn|front-?door/, Globe],
  [/vpc|subnet|route|load-?balanc|\belb\b|\balb\b|\bnlb\b|network|gateway/, Network],
  [/cognito|auth|iam|kms|secret|vault/, Lock],
  [/cloudwatch|monitor|grafana|prometheus|datadog|insight|trace|\blogs?\b/, Activity],
  [/eks|aks|gke|kubernetes|ecs|container|docker/, Boxes],
  [/redis|cache|memcache/, Zap],
  [/user|customer|people/, Users],
  [/\bapi\b|api-?gateway/, Braces],
  [/mail|\bses\b|sendgrid/, Mail],
  [/search|elastic|opensearch|algolia/, Search],
  [/mobile|phone/, Smartphone],
  [/web|browser|frontend/, AppWindow],
  [/\b(ai|ml|llm)\b|sagemaker|bedrock|openai/, Brain],
  [/cloud/, Cloud],
];

import cloudManifest from './cloud-icons.json';

const CLOUD_ICONS = new Set<string>(cloudManifest.icons);
const CLOUD_ALIASES = cloudManifest.aliases as Record<string, string>;

/** Path to an official provider SVG for this icon name, or null when not in the vendored packs. */
export function cloudIconSrc(name?: string): string | null {
  if (!name) return null;
  const key = name.trim().toLowerCase();
  const slug = CLOUD_ICONS.has(key) ? key : CLOUD_ALIASES[key];
  if (!slug) return null;
  return `/icons/${slug.split('-')[0]}/${slug}.svg`;
}

export function resolveIcon(name?: string, hint?: string): LucideIcon {
  for (const candidate of [name, hint]) {
    if (!candidate) continue;
    const key = candidate.trim().toLowerCase();
    if (ICONS[key]) return ICONS[key];
    const stripped = key.replace(/^(aws|azure|gcp|google|tech)-/, '');
    if (ICONS[stripped]) return ICONS[stripped];
    const hit = PATTERNS.find(([re]) => re.test(key));
    if (hit) return hit[1];
  }
  return Box;
}
